### ISSUE TITLE
Suggestion: Price Modifier Option

### ISSUE THREAD

**Issue by Asinphi** [shmkane/SellStick#10]
Hi, do you think you can add a price multiplier option in the Sell Stick plugin with permission nodes? Something that could make items sell for more or less. Something like sellstick.multiplier.2 that you could give to a player and everything they sell via sell stick would be worth double.

**Comment by shmkane** [comment]
It's one of my planned features to add but I haven't had time to implement.

**Comment by shmkane** [comment]
Added to master branch
