### ISSUE TITLE
Compatibility With ShopGUI+

### ISSUE THREAD

**Issue by Asinphi** [shmkane/SellStick#11]
Can you make the Sell Wands plugin compatible with [ShopGUI+](https://www.spigotmc.org/resources/shopgui-admin-gui-shop-plugin.6515/)? They have an API on their page. It would be really useful so server owners don't have to set up both a worth.yml file and their ShopGUI+ shop.

**Comment by shmkane** [comment]
I have gotten a decent amount of requests for this so I will consider it.
