### ISSUE TITLE
Dosen't load

### ISSUE THREAD

**Issue by ghost** [shmkane/SellStick#14]
Hey, i have a issue where the plugin does not load for some reason.
`18.10 13:33:57 [Server] INFO [13:33:57 ERROR]: Could not load 'plugins/SellStick.8.0.8.1.jar' in folder 'plugins'
18.10 13:33:57 [Server] INFO org.bukkit.plugin.UnknownDependencyException: PlotSquared
18.10 13:33:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:222) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
18.10 13:33:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
18.10 13:33:57 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
18.10 13:33:57 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
18.10 13:33:57 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]`

**Comment by shmkane** [comment]
Are you running PlotSquared on your server?

**Comment by ghost** [comment]
no I don't, with is why I found it weird, we're a faction server

**Comment by shmkane** [comment]
Use a different version
![image](https://user-images.githubusercontent.com/2586027/47227597-3e13be00-d391-11e8-8c4f-69d1dc6f1fbc.png)
