### ISSUE TITLE
Right Click Chest Issue!

### ISSUE THREAD

**Issue by ghost** [shmkane/SellStick#2]
Getting this error message in console when ever a player right clicks a chest with the stick > https://hastebin.com/unureciyez.go

**Comment by shmkane** [comment]
Are you running Factions on your server or no?

**Comment by ghost** [comment]
Yes i am FactionsUUID v1.6.9.5-U0.1.20

**Comment by shmkane** [comment]
Sorry for the delay, which version of the plugin are you using? Make sure you have the latest one. If you upgrade to the latest version and still find this issue, let me know

**Comment by gh-doot** [comment]
I think its fixed, he doesn't respond in fact
