### ISSUE TITLE
SellStick Not Working For Me

### ISSUE THREAD

**Issue by JOVO12** [shmkane/SellStick#20]
Please Can You Help Me How To Setup This SellSticks? cause its not working for me i downloaded vault and sell sticks and i did /sellstick [player] 1 1 and its giving but its not working for use im op on my server and i try it too i put in a chest 64 diamonds and on prices i type diamond:1:400 and i put diamond when i left click its not giving money and its not talking the diamonds from the chest. can you help me here? on the messages or at discord: Sleng$wang#0823 Thank You Very Much. Have Nice Day!

**Comment by shmkane** [comment]
The item meta of diamond is not 1, it's 0. 
you could just do DIAMOND:400

I added you on discord if you need further help
