### ISSUE TITLE
PlotSquared Support

### ISSUE THREAD

**Issue by ItzSave** [shmkane/SellStick#21]
When using PaperSpigot-1.12.2 users can sell items from chests on plots that they are not added to.

**Comment by shmkane** [comment]
At the time of someone using a sellstick in plots that are not theirs, see if theres any errors. If there exists errors, https://hastebin.com/ send it using this (or similar)

**Comment by shmkane** [comment]
https://github.com/shmkane/SellStick/releases/tag/v8.1.1.2
