### ISSUE TITLE
SellStick disabling on startup

### ISSUE THREAD

**Issue by Matthew777k** [shmkane/SellStick#26]
Hi,

I'm having an issue with SellStick disabling on startup. This is the error I'm getting even though I'm using SavageFactions 1.4 stable build.
https://hastebin.com/ovopikukih.css

Plugman loading the plugin once it doesn't load correctly fixes the issue for me, so I'm not quite sure what the issue is on startup.

**Comment by Matthew777k** [comment]
Here's an example of me plugman reload'ing it minutes later and it detecting SavageFac's perfectly fine.
https://hastebin.com/efahiqixav.md

**Comment by shmkane** [comment]
Thanks for reporting this. Should be fixed soon

**Comment by shmkane** [comment]
Issue should be resolved now, @Matthew777k
