### ISSUE TITLE
Odd formatting issue

### ISSUE THREAD

**Issue by Matthew777k** [shmkane/SellStick#28]
After updating to the recent version of the faction's version, this started to happen when each sellstick was spawned in.
https://i.imgur.com/ByCNwWi.png

This wasn't happening prior to the update, definitely not something major at all considering the wand's still work perfectly fine. It was just something I found odd and figured I'd report.

Config I'm using if you're curious:
https://hastebin.com/kacutizofo.shell

**Comment by shmkane** [comment]
Sorry about the delay. Should be fixed with the next release (few minutes now)
