### ISSUE TITLE
Or we can download the plugin

### ISSUE THREAD

**Issue by Con3ction** [shmkane/SellStick#31]
Download link doesn't work

**Comment by Con3ction** [comment]
@shmkane

**Comment by shmkane** [comment]
All the download links work, just tested. Send me what isn't working for you.

**Comment by shmkane** [comment]
https://gyazo.com/ed84236c647ce258e4fdb47321040678

**Comment by Con3ction** [comment]
Ah, I did not understand her ... as much for me. But ducoup he esxiste not for simple survival? or you absolutely must have Askyblock or faction ...

**Comment by shmkane** [comment]
Currently you must have ASkyBlock or factions

**Comment by Con3ction** [comment]
thin this damage but not serious thank you: D
