### ISSUE TITLE
BSkyblock compatibility

### ISSUE THREAD

**Issue by OGreenC** [shmkane/SellStick#33]
Hi,

Could you please add support for the BSkyblock plugin?

They have a pretty extensive API (Bentobox). 
A link to their Git: https://github.com/BentoBoxWorld/BentoBox

Looking forward to hear from you!

**Comment by shmkane** [comment]
I'm currently not going to be adding support for new plugins. As you said, they have an extensive API and my plugin is open source. You are more than welcome to add it!
