### ISSUE TITLE
Plugin does not work with BeerSpigot JAR

### ISSUE THREAD

**Issue by macosxuser** [shmkane/SellStick#34]
An internal error occured while attempting to perform this command when I do /sellstick
INFO org.bukkit.command.CommandException: Unhandled exception executing command 'sellstick' in plugin SellStick v8.1.0.5U
25.04 20:57:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1178) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:991) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
25.04 20:57:43 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
25.04 20:57:43 [Server] INFO Caused by: java.lang.NullPointerException
25.04 20:57:43 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO at com.acropolismc.play.sellstick.SellStickCommand.onCommand(SellStickCommand.java:66) ~[?:?]
25.04 20:57:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
25.04 20:57:43 [Server] INFO ... 15 more

**Comment by shmkane** [comment]
The plugin does not claim to work with BeerSpigot
