### ISSUE TITLE
Plugin issues after editing lore

### ISSUE THREAD

**Issue by valkyriecraftmc** [shmkane/SellStick#37]
Hello! The plugin works great out of the box, so to speak. But after I edit the lore, it stops working completely. Doesn't even give me any feedback when I type /sellstick 

Any solutions? Running this on spigot 1.8.8 With FactionsUUID.

**Comment by shmkane** [comment]
Hello,

When you start the server up, check for errors.

**Comment by valkyriecraftmc** [comment]
19.08 16:34:36 [Server] INFO Enabling SellStick v8.1.0.5U
19.08 16:34:36 [Server] ERROR Cannot load plugins/SellStick/config.yml
19.08 16:34:36 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
19.08 16:34:36 [Server] INFO in 'string', line 31, column 1:
19.08 16:34:36 [Server] INFO AllowedInFactionClaim: true
19.08 16:34:36 [Server] INFO ^
19.08 16:34:36 [Server] INFO expected <block end>, but found Scalar
19.08 16:34:36 [Server] INFO in 'string', line 227, column 40:
19.08 16:34:36 [Server] INFO ... ssionMessage: '&cSorry, you don't have permission for this!'
19.08 16:34:36 [Server] INFO ^
19.08 16:34:36 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at com.acropolismc.play.sellstick.Configs.StickConfig.loadValues(StickConfig.java:41) [SellStick8.1.0.5U.jar:?]
19.08 16:34:36 [Server] INFO at com.acropolismc.play.sellstick.Configs.StickConfig.setup(StickConfig.java:118) [SellStick8.1.0.5U.jar:?]
19.08 16:34:36 [Server] INFO at com.acropolismc.play.sellstick.SellStick.onEnable(SellStick.java:28) [SellStick8.1.0.5U.jar:?]
19.08 16:34:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
19.08 16:34:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
19.08 16:34:36 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
19.08 16:34:37 [Server] Startup Done (12.325s)! For help, type "help" or "?"

**Comment by shmkane** [comment]
Hello,

Could you try resetting the config, then editing the values one at a time to see which one is causing the issues for you? I tried on my end and it seems to be working fine.

**Comment by valkyriecraftmc** [comment]
Hmmm.... Interesting. When I edited everything one by one and reloaded each time, it worked everytime. I apologize for wasting your time. Thank you!

**Comment by shmkane** [comment]
Not a waste of time at all. Maybe there was some weird character you
accidentally inputted. Glad it worked out in the end though.

**Comment by valkyriecraftmc** [comment]
Now if I could just get it to sell! haha. I'll let my dev work that one out. Thanks man!

**Comment by shmkane** [comment]
What issue are you having with selling?

**Comment by valkyriecraftmc** [comment]
Click on a chest, and nothing happens

**Comment by shmkane** [comment]
Any errors?

**Comment by valkyriecraftmc** [comment]
Now I'm just really puzzled. Restarted the server at I get:

19.08 17:19:15 [Server] INFO Disabling SellStick v8.1.0.5U

Everything else booted appropriately

**Comment by shmkane** [comment]
Could you send a full log of the start up (Or atleast 5-10 lines above that and 5-10 lines below)

**Comment by valkyriecraftmc** [comment]
So, I reloaded with a fresh config file, and now it works? I'm probably going to have to go through one by one again and see which one breaks it

**Comment by shmkane** [comment]
Seems like you're not having the best time. If you want, add me on discord and I can provide faster support : shmkane # 0001

**Comment by valkyriecraftmc** [comment]
apparently I can't even do that right either -_-' lol it wont find your name, can you try mine? project_56@5773

**Comment by shmkane** [comment]
Sent
