### ISSUE TITLE
Selling Issues

### ISSUE THREAD

**Issue by GemcraftServer** [shmkane/SellStick#40]
The plugin is not registering some items that are in the prices.yml file. It is incorrectly saying that these items are not worth selling. These are the items that are not working:

  GUNPOWDER:
  COOKED_PORKCHOP
  LAPIS_LAZULI
  PUMPKIN
  MELON
  CARROT
  POTATO
  WHEAT
  SUGAR_CANE

**Comment by HunterJacobs** [comment]
Also encountering this issue, would love it if you could fix!

**Comment by shmkane** [comment]
A fix for these will be up today
