### ISSUE TITLE
Usage in truce claims // owned chunks // recode

### ISSUE THREAD

**Issue by srleojaco** [shmkane/SellStick#41]
Hey there!

I've been using the plugin, but i'm lacking an option for truce claims (because at the moment players are able to use the stick on those claims cause there's no option).

Also, owned chunks (in SavageFactions) allow the player to use the sellstick when they've no perms in that chunks.

So i'd suggest a recode for plugin: **checking player's perms for the territory** so **if the player has CONTAINER perm** he should be able to use the stick.

This would allow faction's admin to control the sellstick usage for their own faction

**Comment by shmkane** [comment]
Hi, sorry for the delay in response. The way sellstick is currently configured to work is to check if another plugin is blocking interactions to a chest. If that's the case, sellstick will NOT sell. What this usually means is that if you can open a chest, you can sell contents of a chest.

I can't, unfortunately, go through and add exceptions and causes for each plugin.

If you feel that your issue describes a different case (If you cant open chests but you can still sell from them) that's definitely something I can look into fixing.
