### ISSUE TITLE
j

### ISSUE THREAD

**Issue by cra1gg** [shmkane/SellStick#45]
**Is your feature request related to a problem? Please describe.**
YEA BOI
**Describe the solution you'd like**
MORE STICKS
**Describe alternatives you've considered**
FACTIONS
**Additional context**
guacamole

**Comment by shmkane** [comment]
solved

**Comment by cra1gg** [comment]
Hi,
I just updated my problem. Please consider it.

yours truly,
megaman900

**Comment by shmkane** [comment]
consider it considerably considered
