### ISSUE TITLE
Plotsquared protection issue

### ISSUE THREAD

**Issue by Woeben** [shmkane/SellStick#51]
**Describe the bug**
Only when SHIFT clicking a chest you can sell items on not owned plots
**To Reproduce**
1. Install plotsquared
2. shift right click on a chest in a not owned plot

**Expected behavior**
You will sell items from others. HUGE problem

**Screenshots**

**Server Info(please complete the following information):**
 - Version 1.15.2 Paper
 - SellStick version LATEST

**Additional context**
Please upload your config.yml as well as prices.yml and any additional files necessary

**Comment by shmkane** [comment]
Thanks for reporting this. I'll take a look today
