### ISSUE TITLE
Hook with the iridium skyblock plugin

### ISSUE THREAD

**Issue by garsh1** [shmkane/SellStick#60]
I can't use the plugin because I don't have any of the plugins that allow me to be in "Valid territory". I run a Skyblock server that uses Iridium Skyblock. Would it be possible to hook with the iridium Skyblock plugin?

**Comment by shmkane** [comment]
By default, how sellstick works is that it checks to see if any other plugin has denied access to opening a chest.

Put another way: if a player is able to open (rightclick) a chest, they are able to sell from it. 

What this means is that it SHOULD work with your skyblock plugin.

**Some people have mentioned that there's a bug where Admins/Mods get a message stating "They cant sell from this chest," but this does not affect regular players.** 

What I suggest you do is open a private server/whitelist your sever with sellstick added and see if it works on your skyblock islands as it should. Be sure to test with `regular` players and not admins!

If you're still not successful, let me know by updating this Issue, or on the discord. Discord and downloads found here http://sellstick.shmkane.com/

**Comment by DEADLYDEVIL-IR** [comment]
> 
> 
> By default, how sellstick works is that it checks to see if any other plugin has denied access to opening a chest.
> 
> Put another way: if a player is able to open (rightclick) a chest, they are able to sell from it.
> 
> What this means is that it SHOULD work with your skyblock plugin.
> 
> **Some people have mentioned that there's a bug where Admins/Mods get a message stating "They cant sell from this chest," but this does not affect regular players.**
> 
> What I suggest you do is open a private server/whitelist your sever with sellstick added and see if it works on your skyblock islands as it should. Be sure to test with `regular` players and not admins!
> 
> If you're still not successful, let me know by updating this Issue, or on the discord. Discord and downloads found here http://sellstick.shmkane.com/

yea admins in iridiumskyblock are having problem to use sell stick

**Comment by shmkane** [comment]
> > By default, how sellstick works is that it checks to see if any other plugin has denied access to opening a chest.
> > Put another way: if a player is able to open (rightclick) a chest, they are able to sell from it.
> > What this means is that it SHOULD work with your skyblock plugin.
> > **Some people have mentioned that there's a bug where Admins/Mods get a message stating "They cant sell from this chest," but this does not affect regular players.**
> > What I suggest you do is open a private server/whitelist your sever with sellstick added and see if it works on your skyblock islands as it should. Be sure to test with `regular` players and not admins!
> > If you're still not successful, let me know by updating this Issue, or on the discord. Discord and downloads found here http://sellstick.shmkane.com/
> 
> yea admins in iridiumskyblock are having problem to use sell stick

Hi, sorry for the delay, if you're still having troubles, I suggest contacting me on Discord
