### ISSUE TITLE
Sellstick 1.8.8 giveall

### ISSUE THREAD

**Issue by LudnicaKiller** [shmkane/SellStick#61]
Please check all the boxes in order for this to be considered.

[ ] I acknowledge SellStick is an open source plugin, meaning I have access to the source code and I could make this feature myself.
[x] I agree that this feature is not too large or unfeasbile.
[ ] I agree that I totally haven't read any of these I'm just checking the boxes.
[x] I acknowledge that I've looked around for another plugin to do this task but one isn't available.
[x] I agree that shmkane is awesome and this bullet is just here so you know how to check a box.
[ ] I agree that this feature request may be ignored, closed, or laughed at because shmkane is very busy.

**Please describe your feature request in a couple sentences**
I want giveall feature for sellstick on 1.8.8.

**Comment by shmkane** [comment]
Firstly, 2 of your checks are missing, which is why I didn't look at this. Secondly, I don't have any intent on adding this feature for 1.8.8. It exists for 1.15+ if you need https://github.com/shmkane/SellStick/releases/tag/beta1.15
