### ISSUE TITLE
Console spam! (1.12.2)

### ISSUE THREAD

**Issue by ghost** [shmkane/SellStick#8]
When I use the want as a player without permission to the area on spawn it shows a huge error in the console, also could You make all of the messages customizeable?

**Comment by shmkane** [comment]
Please send the huge error in console. Which messages would you like customizable?

**Comment by ghost** [comment]
Thanks for fast response, I's 3 am for me, I will send you all of the details tomorrow :)

**Comment by shmkane** [comment]
Sure thing. Be sure to also include what version of factions you're using, and make sure you're using the latest version of the plugin

**Comment by ghost** [comment]
I'm not using factions plugin, only askyblock, cause it's a skyblock server. Log:
[lom.txt](https://github.com/shmkane/SellStick/files/2194955/lom.txt)
I want to customize the console message and the message when you recieve the stick

**Comment by shmkane** [comment]
I'll have to look into it after this weekend

**Comment by shmkane** [comment]
Hello, what version of ASkyBlock are you currently using?

**Comment by ghost** [comment]
The latest one

**Comment by shmkane** [comment]
Check out the latest version of sellstick and let me know if it fixes your issue
https://www.spigotmc.org/resources/sell-stick-sell-wand.38119/

**Comment by ghost** [comment]
Will check asap, also good job with the plugin

śr., 18 lip 2018, 01:26 użytkownik shmkane <notifications@github.com>
napisał:

**Comment by shmkane** [comment]
Thanks! If you could, please leave a review on the spigot page :)
