### ISSUE TITLE
Sellstick usage in faction claims

### ISSUE THREAD

**Issue by JGuerndt** [shmkane/SellStick#9]
Right click on a faction's chest, says this faction does not allow you to use containers. Left click with sell stick, it allows you to sell items from another factions chest. Using Massive Core factions and that is the only one set to true in the config. Only wilderness and within own faction are set to true in other section in config.

**Comment by shmkane** [comment]
I'm assuming the issue still exists.

So if I understood properly:

If you're using MCore factions and you try to open a chest which you don't have access to, you can still sell the contents of it?

Are you currently using the latest version of the plugin? 

Furthermore, can you send your config.yml here.

**Comment by shmkane** [comment]
Assuming this issue has been resolved

**Comment by JGuerndt** [comment]
Apologies for the delay, below is the config.

#############################
####Sell Stick by shmkane####
#############################
#
# Config Version: 8.0 -- Don't change this value!
#
###################
# Server Settings #
###################
#
#
#Firstly, enable which factions plugin you are using
#Note: Savage Factions is a fork of UUID, so selecting
#Either is fine but DONT select both!
UsingLegacyFactions: false
UsingFactionsUUID: false
UsingSavageFactions: false
UsingMCoreFactions: true
#If you're running ASkyBlock, enable this option.
UsingSkyBlock: false
###############
#FACTIONS ONLY# - Ignore these 4 settings if you're not using factions!
###############
#
#Where should sellstick be allowed
#Note: If you renamed Safezone/Warzone/Wilderness to something else(like SafeArea, KillArea, WildArea), this will break!
#Contact me and I can arrange something for you!
#Contact info at bottom
#
#Can players use sellstick in their own claims?
AllowedInFactionClaim: true
#Can players use sellstick in safezone?
AllowedInSafezoneClaim: false
#Can players use sellstick in warzone?
AllowedInWarzoneClaim: false
#Can players use sellstick in wilderness?
AllowedInWildernessClaim: true
#
##################
# Stick Settings #
##################
#
#This is the part you edit regardless of factions or skyblock!
#
#The name of the item - displayname
DisplayName: '&4&lInflux&6&lStick'
#
#----------------------------------------#
#For any Materials, use 
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html as a reference
####YES IT MATTERS HOW YOU TYPE IT IN####
#####PLEASE GO TO THAT LINK######
#----------------------------------------#
#
#Use the above link to change this item from a stick to anything else
ItemType: STICK #ONCE AGAIN, USE THE LINK ABOVE FOR ITEM NAMES
#
#
#The lore on the stick
#When they hover over it, what do they see
#Line 2 will always be the Finite or Infinite Lore
StickLore:
- '&f&lLeft&f click on a chest to sell items inside!' #line 1
#The Finite or Infinite lore will go here.
#- '&cAsk an admin to customize this!' #line 4
#- '&cadd more lines' #line 5
#- '&aLike this' #line 6
#
#
#If they have a Finite stick(non-infinite)
#Please try not to include any other numbers
#in this lore
FiniteLore: '&c%remaining% &fremaining uses'
#
#
#If they have an infinite stick, the lore
#This will be the 2nd line
InfiniteLore: '&4Infinite &6uses!'
#
#
#Messages sent to the palyer will be prefixed with this
MessagePrefix: '&f[&6Influx&6Stick&f] &e'
#
#
#When they sell the items what message should be displayed
#Use %price% for how much they gained
#use %balance% to show new balance
SellMessage: '&fYou sold items for &a%price% &fand now have &a%balance%'
#
#
#If they don't have permission to do something
NoPermissionMessage: '&cSorry, you don''t have permission for this!'
#
#
#If they try using the stick in an invalid territory. FACTIONS ONLY
InvalidTerritoryMessage: '&cYou can''t use sell stick in these claims!'
#
#
#If the chest chest didnt have anything they could sell
#Meaning, if the items in the chest didnt appear in the Price.yml
NotWorthMessage: '&cNothing worth selling inside'
#
#
#What message is sent if they run out of uses?
BrokenStick: '&cYour sellstick broke!(Ran out of uses)'
#
#
#Do you want to use essentials worth.yml for your prices
#instead of my prices.yml?
#if so, enable this
UseEssentialsWorth: true
#
#
#The message to send to the Admin who gave the sticks
GiveMessage: '&aYou gave &e%player% &e&l%amount% &asell sticks!'
#
#
#Message to send to the player who received the sticks
ReceiveMessage: '&aYou''ve received &e&l%amount% &asell sticks!'
#
#That's it! If you have questions, ask on Spigot or GitHub.
#I typically respond faster on GitHub
#https://github.com/shmkane/SellStick
#https://www.spigotmc.org/resources/sell-stick.38119/
#You can also email me, shmkane@gmail.com
#just let me know in the subject it's regarding
#Sellstick or I may not repond :P

**Comment by shmkane** [comment]
So the issue is that if you don't have access to a chest in your faction territory you can still sell the contents of it?

**Comment by JGuerndt** [comment]
Correct. Player from faction A goes to faction B - can not access chests, but can use sell stick to sell contents of faction B's chests.
